### ISSUE TITLE
Hello from a peer in Nomad Coders

### ISSUE THREAD

**Issue by ystime25** [GitHubGW/Socket.IO-Chat#1]
Hello GitHubGW
I am currently learning about socket.io with Nomad Coders reality game. But I have an error that you don't seem to have. If you have time could you please help me out?

The code location I have problem with is in assets/js/chat js 
and the code is bellow
getSocket().emit(window.events.sendMsg, { message: value }); 

I have error after entering a message on the chat. (error message below)
Uncaught TypeError: Cannot read property 'emit' of undefined
    at HTMLFormElement.handleSendMsg

my commit containing the error is
https://github.com/ystime25/catchmindjs/commit/7c3b86ba7fd3a6710726a9e039fbe98320e31925

hope you can help me out thank you :)

**Comment by ystime25** [comment]
found out it was an issue with versions of packages
sorry for the hassle

**Comment by GitHubGW** [comment]
Did you solve the problem?
I'm glad if you solved the problem.
Cheer up! Fighting!

**Comment by GitHubGW** [comment]
> found out it was an issue with versions of packages
> sorry for the hassle

Did you solve the problem?
I'm glad if you solved the problem.
Cheer up! Fighting!
